apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  labels:
    app: {{ .Release.Name }}-backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: {{ .Values.backend.service.port }}
  selector:
    app: {{ .Release.Name }}-backend
