apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-service
  labels:
    app: {{ .Release.Name }}-database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: {{ .Values.database.service.port }}
  selector:
    app: {{ .Release.Name }}-database
