apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-database-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-database-deployment
  minReplicas: {{ .Values.database.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.database.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.database.autoscaling.targetCPUUtilizationPercentage }}
