apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: {{ .Release.Name }}-frontend
