apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.database.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.database.storageClass.size }}
