apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-secret
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
